// <auto-generated />
using System;
using CustomInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomInventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509161644_AddCategoryUniqueIndex")]
    partial class AddCategoryUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomInventory.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CustomInventory.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomBool1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomBool2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomBool3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomInt1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomInt2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomInt3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText3State")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("CustomInventory.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CustomBool1Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CustomBool2Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CustomBool3Value")
                        .HasColumnType("boolean");

                    b.Property<double?>("CustomInt1Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("CustomInt2Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("CustomInt3Value")
                        .HasColumnType("double precision");

                    b.Property<string>("CustomLink1Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomLink2Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomLink3Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomString1Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomString2Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomString3Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomText1Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomText2Value")
                        .HasColumnType("text");

                    b.Property<string>("CustomText3Value")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "Id")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CustomInventory.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("CustomInventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CustomInventory.Domain.Entities.Item", b =>
                {
                    b.HasOne("CustomInventory.Domain.Entities.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CustomInventory.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
